spring:
  main:
    banner-mode: "off"
  application:
    name: eureka-ribbon 
  cloud:
    loadbalancer:
      retry:
        enabled: true     
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
