server:
  port: 8123
  context-path: /apis
spring:
  mail:
    host: smtp.163.com
    username: 13649283825@163.com
    password: 153246w
    
  application:
    name: api
  profiles:
    active: ${profiles}
  cloud:
    config:
#     在本地测试时，下面的uri需要改成自己的product-config-server项目所在的服务器地址,目前的配置是部署在服务的config-server配置
      uri: http://localhost:8888/configserver/
      label: master
      fail-fast: true
security:
  oauth2:
    resource:
      jwt:
        key-value: secret