spring:
  rabbitmq:
    addresses: 132.232.89.207:5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5 #最大并发数
        acknowledge-mode: AUTO
        max-concurrency: 10
        prefetch: 1 #限流
        
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 9012
      