spring:
  main:
    banner-mode: "off"
  application:
    name: eureka-hystrix
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
